from .least_seen_af import LeastSeenAF
from .random_af import RandomAF
from .likeliest_draw_af import LikeliestDrawAF
from .likeliest_win_af import LikeliestWinAF
from .trueskill_af import TSQualityAF
from .most_seen_af import MostSeenAF
from .weighted_overengineer_af import WeightedComplexAF
from .weighted_af import WeightedAF
from .cheating_af import CheatingAF
from .ce_af import CrossEntropyAF